/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administration;

/**
 *
 * @author isai
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miAddUser = new javax.swing.JMenuItem();
        miEditUser = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miAddPay = new javax.swing.JMenuItem();
        miEditPay = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miAddEmployee = new javax.swing.JMenuItem();
        miEditEmployee = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        miAddCustomer = new javax.swing.JMenuItem();
        miEditCustomer = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 781, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        jMenu1.setText("Usuarios");

        miAddUser.setText("Crear usuario");
        miAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddUserActionPerformed(evt);
            }
        });
        jMenu1.add(miAddUser);

        miEditUser.setText("Editar usuario");
        miEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEditUserActionPerformed(evt);
            }
        });
        jMenu1.add(miEditUser);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Métodos de pago");

        miAddPay.setText("Añadir método de pago");
        miAddPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddPayActionPerformed(evt);
            }
        });
        jMenu2.add(miAddPay);

        miEditPay.setText("Editar método de pago");
        jMenu2.add(miEditPay);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Empleados");

        miAddEmployee.setText("Agregar empleado");
        jMenu3.add(miAddEmployee);

        miEditEmployee.setText("Editar empleado");
        jMenu3.add(miEditEmployee);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Clientes");

        miAddCustomer.setText("Añadir cliente");
        jMenu4.add(miAddCustomer);

        miEditCustomer.setText("Editar cliente");
        jMenu4.add(miEditCustomer);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddUserActionPerformed
        User_Window userWindow = new User_Window();
        userWindow.setVisible(true);
    }//GEN-LAST:event_miAddUserActionPerformed

    private void miEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEditUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miEditUserActionPerformed

    private void miAddPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddPayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miAddPayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem miAddCustomer;
    private javax.swing.JMenuItem miAddEmployee;
    private javax.swing.JMenuItem miAddPay;
    private javax.swing.JMenuItem miAddUser;
    private javax.swing.JMenuItem miEditCustomer;
    private javax.swing.JMenuItem miEditEmployee;
    private javax.swing.JMenuItem miEditPay;
    private javax.swing.JMenuItem miEditUser;
    // End of variables declaration//GEN-END:variables
}
