/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administration;

import Products.Inventary_Window;
import Products.Product_Window;

/**
 *
 * @author isai
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miAdUser = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miAdEmployee = new javax.swing.JMenuItem();
        miAdCustomer = new javax.swing.JMenu();
        miAddCustomer = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        miAdProducts = new javax.swing.JMenuItem();
        miInventary = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 781, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        jMenu1.setText("Usuarios");

        miAdUser.setText("Administrar Usuarios");
        miAdUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAdUserActionPerformed(evt);
            }
        });
        jMenu1.add(miAdUser);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Empleados");

        miAdEmployee.setText("Administrador de empleados");
        miAdEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAdEmployeeActionPerformed(evt);
            }
        });
        jMenu3.add(miAdEmployee);

        jMenuBar1.add(jMenu3);

        miAdCustomer.setText("Clientes");

        miAddCustomer.setText("Administrador de clientes");
        miAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddCustomerActionPerformed(evt);
            }
        });
        miAdCustomer.add(miAddCustomer);

        jMenuBar1.add(miAdCustomer);

        jMenu4.setText("Productos");

        miAdProducts.setText("Administrador de Productos");
        miAdProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAdProductsActionPerformed(evt);
            }
        });
        jMenu4.add(miAdProducts);

        miInventary.setText("Inventario");
        miInventary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miInventaryActionPerformed(evt);
            }
        });
        jMenu4.add(miInventary);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAdUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAdUserActionPerformed
        User_Window userWindow = new User_Window();
        userWindow.setVisible(true);
    }//GEN-LAST:event_miAdUserActionPerformed

    private void miAdProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAdProductsActionPerformed
        Product_Window productWindow = new Product_Window();
        productWindow.setVisible(true);
    }//GEN-LAST:event_miAdProductsActionPerformed

    private void miInventaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miInventaryActionPerformed
        Inventary_Window inventaryWindow = new Inventary_Window();
        inventaryWindow.setVisible(true);
    }//GEN-LAST:event_miInventaryActionPerformed

    private void miAdEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAdEmployeeActionPerformed
        Employee_Window employeeWindow = new Employee_Window();
        employeeWindow.setVisible(true);
    }//GEN-LAST:event_miAdEmployeeActionPerformed

    private void miAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddCustomerActionPerformed
        Customer_Window customerWindow = new Customer_Window();
        customerWindow.setVisible(true);
    }//GEN-LAST:event_miAddCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu miAdCustomer;
    private javax.swing.JMenuItem miAdEmployee;
    private javax.swing.JMenuItem miAdProducts;
    private javax.swing.JMenuItem miAdUser;
    private javax.swing.JMenuItem miAddCustomer;
    private javax.swing.JMenuItem miInventary;
    // End of variables declaration//GEN-END:variables
}
